"""
TikTok Publisher API — VideoMachine SaaS
Uploads short-form videos (generated by YouTube pipeline or uploaded manually)
to TikTok via the official Content Posting API.
"""
from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import Optional, List
from datetime import datetime
from app.core.database import get_db
from app.core.security import get_active_user
from app.models.task import Task
from app.models.user import User
from app.services.mp_wrapper import run_tiktok_post

router = APIRouter(prefix="/api/tiktok", tags=["tiktok"])


class TikTokPostInput(BaseModel):
    # Path to an existing generated video (from YouTube task) or uploaded file
    video_path: str
    topic: str
    custom_caption: Optional[str] = None
    privacy: str = "PUBLIC_TO_EVERYONE"   # PUBLIC_TO_EVERYONE | FOLLOWER_OF_CREATOR | SELF_ONLY


class TaskOut(BaseModel):
    id: int
    status: str
    tweet_content: Optional[str]   # used to store TikTok caption
    youtube_url: Optional[str]     # used to store TikTok publish_id
    error_message: Optional[str]
    logs: Optional[str]
    created_at: datetime
    completed_at: Optional[datetime]

    class Config:
        from_attributes = True


@router.post("/post", response_model=TaskOut)
async def post_tiktok(
    data: TikTokPostInput,
    background_tasks: BackgroundTasks,
    current_user: User = Depends(get_active_user),
    db: Session = Depends(get_db),
):
    cfg = current_user.mp_config or {}
    if not cfg.get("tiktok_cookies"):
        raise HTTPException(400, "Cookies TikTok requis. Configurez-les dans Paramètres → TikTok.")

    task = Task(
        owner_id=current_user.id,
        task_type="tiktok",
        status="pending",
        title=f"TikTok: {data.topic[:60]}",
        niche=data.topic,
        tweet_content=data.custom_caption,
        logs="",
    )
    db.add(task)
    db.commit()
    db.refresh(task)

    from app.core.database import SessionLocal

    async def bg(tid, video_path, topic, caption, privacy, config):
        bg_db = SessionLocal()
        try:
            await run_tiktok_post(tid, video_path, topic, caption, privacy, config, bg_db)
        finally:
            bg_db.close()

    background_tasks.add_task(
        bg, task.id, data.video_path, data.topic,
        data.custom_caption, data.privacy, cfg,
    )
    return task


@router.post("/post-from-task/{youtube_task_id}", response_model=TaskOut)
async def post_from_youtube_task(
    youtube_task_id: int,
    topic: str = "",
    custom_caption: Optional[str] = None,
    privacy: str = "PUBLIC_TO_EVERYONE",
    background_tasks: BackgroundTasks = BackgroundTasks(),
    current_user: User = Depends(get_active_user),
    db: Session = Depends(get_db),
):
    """Republish an already-generated YouTube Short to TikTok."""
    cfg = current_user.mp_config or {}
    if not cfg.get("tiktok_cookies"):
        raise HTTPException(400, "Cookies TikTok requis. Configurez-les dans Paramètres → TikTok.")

    yt_task = db.query(Task).filter(
        Task.id == youtube_task_id,
        Task.owner_id == current_user.id,
        Task.task_type == "youtube",
        Task.status == "completed",
    ).first()
    if not yt_task:
        raise HTTPException(404, "Tâche YouTube introuvable ou non terminée.")
    if not yt_task.video_path:
        raise HTTPException(400, "Aucune vidéo associée à cette tâche YouTube.")

    task_topic = topic or yt_task.niche or yt_task.title or "video"
    task = Task(
        owner_id=current_user.id,
        task_type="tiktok",
        status="pending",
        title=f"TikTok (de YT#{youtube_task_id}): {task_topic[:50]}",
        niche=task_topic,
        tweet_content=custom_caption,
        logs="",
    )
    db.add(task)
    db.commit()
    db.refresh(task)

    from app.core.database import SessionLocal

    async def bg(tid, video_path, t, caption, priv, config):
        bg_db = SessionLocal()
        try:
            await run_tiktok_post(tid, video_path, t, caption, priv, config, bg_db)
        finally:
            bg_db.close()

    background_tasks.add_task(
        bg, task.id, yt_task.video_path,
        task_topic, custom_caption, privacy, cfg,
    )
    return task


@router.get("/posts", response_model=List[TaskOut])
async def list_posts(
    skip: int = 0, limit: int = 50,
    current_user: User = Depends(get_active_user),
    db: Session = Depends(get_db),
):
    return (db.query(Task)
            .filter(Task.owner_id == current_user.id, Task.task_type == "tiktok")
            .order_by(Task.created_at.desc())
            .offset(skip).limit(limit).all())


@router.get("/posts/{task_id}/status")
async def get_status(
    task_id: int,
    current_user: User = Depends(get_active_user),
    db: Session = Depends(get_db),
):
    task = db.query(Task).filter(
        Task.id == task_id, Task.owner_id == current_user.id
    ).first()
    if not task:
        raise HTTPException(404, "Tâche introuvable")
    return {
        "id": task.id,
        "status": task.status,
        "caption": task.tweet_content,
        "publish_id": task.youtube_url,
        "logs": task.logs,
        "error_message": task.error_message,
    }
